---
title: "Mini Project 3"
output: 
  html_document:
    code_folding: hide
---
Abby Allen and Naomi Forman-Katz
```{r, message=FALSE}
#libraries----
library(tidyverse)
library(sf)
library(macleish)
library(leaflet)
library(rgdal)
library(lwgeom)
```

```{r, message=FALSE}
contour_30ft_view <- pluck(macleish_layers[["contours_30ft"]])
contour_3m_view <- pluck(macleish_layers[["contours_3m"]])
```

```{r}
trails_length_test <- macleish_layers %>%
  pluck("trails") %>%
  mutate(computed_length = st_length(geometry))

trails_length <- trails_length_test %>% 
  group_by(name)%>%
  summarize(N = n(), total_length=sum(computed_length))
```

```{r, message=FALSE}
trails_contour_join<-st_join(trails_length,contour_3m_view,join = st_intersects,left=TRUE)
```

```{r, message=FALSE}
trails_length$total_length <- as.numeric(str_extract(trails_length$total_length, "[0-9]+"))

trails_grouped  <-trails_contour_join %>%
  group_by(name) %>%
  summarize(N = n(), max_elevation=max(ELEV_FT,na.rm = TRUE),total_length=mean(total_length,na.rm = TRUE),min_elevation=min(ELEV_FT,na.rm = TRUE)) %>% 
  mutate(SHD_number=(sqrt((max_elevation-min_elevation)*2*(total_length*0.000621371))))%>% 
  mutate(difficulty = ifelse(SHD_number < 10, "Easy",
              ifelse(SHD_number < 20, "Moderate", 
              ifelse(SHD_number < 30, "Difficult",
                     "N/A"))))
```


```{r, message=FALSE}
pal <- colorFactor(c("orange","green", "yellow"),
 trails_grouped %>%
 pull(difficulty) 
 
)
```


```{r, message=FALSE, warning=FALSE}

boundary <- macleish_layers %>%
  pluck("boundary")

trails_inside <- boundary %>%
  st_intersection(trails_grouped)

macleish_map <- leaflet(trails_inside) %>%
  addTiles() %>%
  addPolygons(data = boundary, weight = 1.25, fillColor= "#E4FAFF")

map_color<-macleish_map %>%
  addPolylines(data = contour_3m_view, weight = .5) %>% 
  addPolylines(data = trails_inside,color = ~pal(difficulty)) %>%  
  addLegend("bottomright",pal = pal, values = ~difficulty, opacity = 1)


map_color
```


```{r}
x <- st_intersection(
  pluck(macleish_layers, "trails"), 
  pluck(macleish_layers, "contours_30ft")
)
western <- filter(x, name == "Western Loop")
western_pts <- western %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

snowmobile <- filter(x, name == "Snowmobile Trail")
snowmobile_pts <- snowmobile %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

eastern <- filter(x, name == "Eastern Loop")
eastern_pts <- eastern %>% 
  st_cast("MULTIPOINT")

driveway <- filter(x, name == "Driveway")
driveway_pts <- driveway %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

eastern_line <- eastern_pts %>% 
  st_cast("LINESTRING")

```

```{r}
map_trails<- leaflet(trails_grouped) %>%
  addTiles() %>%
  addPolylines()

map_trails
```















